// ADF_2.0.0/javascript-api/angular2/src/app/app.component.ts
import { Component } from '@angular/core';
import * as AlfrescoApi from 'alfresco-js-api';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  alf;

  files = [];

  tasks = [];

  constructor() {
    this.alf = new AlfrescoApi({
      hostEcm: 'http://localhost:8888',
      hostBpm: 'http://localhost:8888',
      provider: 'ALL'
    });

    this.login();
  }

  login() {
    this.alf.login('admin', 'admin').then(data => {
        console.log('API called successfully Login in performed ', data);

        this.getTasks();

        this.getFiels();
      },
      error => {
        console.log('Error', error);
      }
    );
  }

  getFiels() {
    this.alf.core.nodesApi.getNodeChildren('-my-').then(data => {
        console.log('requestNodes ', data);
        this.files = data.list.entries;
      },
      error => {
        console.log('Error', error);
      });
  }

  getTasks() {
    const requestTasks = new this.alf.activiti.TaskQueryRequestRepresentation();

    this.alf.activiti.taskApi.listTasks(requestTasks).then(data => {
        console.log('listTasks ', data);
        this.tasks = data.data;
      },
      error => {
        console.log('Error', error);
      });
  }

}

<div style="text-align:center">
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>

<div align="center"><b>Tasks</b></div>
<table align="center" border="1" *ngIf="tasks.length">
  <tr>
    <td>id</td>
    <td>name</td>
  </tr>
  <tr *ngFor="let task of tasks">
    <td>{{task.id}}</td>
    <td>{{task.name}}</td>
  </tr>
</table>

<br><br><br>

<div align="center"><b>Files</b></div>
<table align="center" border="1" *ngIf="files.length">
  <tr>
    <td>id</td>
    <td>name</td>
  </tr>
  <tr  *ngFor="let file of files">
    <td>{{file.entry.id}}</td>
    <td>{{file.entry.name}}</td>
  </tr>
</table>

// ADF_2.0.0/javascript-api/react/src/App.js
import React, {Component} from 'react';
import logo from './logo.svg';
import './App.css';
import * as AlfrescoApi from 'alfresco-js-api';

class App extends Component {

    constructor(props) {
        super(props);

        this.alf = new AlfrescoApi({
            hostEcm: 'http://localhost:8888',
            hostBpm: 'http://localhost:8888',
            provider: 'ALL'
        });

        this.state = {
            tasks: [],
            files: []
        };
    }

    componentDidMount() {
        this.login();
    }

    login(){
        this.alf.login('admin', 'admin').then(data => {
                console.log('API called successfully Login in performed ', data);

                this.getTasks();

                this.getFiels();
            },
            error => {
                console.log('Error', error);
            }
        );
    }

    getFiels() {
        this.alf.core.nodesApi.getNodeChildren('-my-').then(data => {
                console.log('requestNodes ', data);
                this.setState({files: data.list.entries});
            },
            error => {
                console.log('Error', error);
            });
    }

    getTasks() {
        var requestTasks = new this.alf.activiti.TaskQueryRequestRepresentation();

        this.alf.activiti.taskApi.listTasks(requestTasks).then(data => {
                console.log('listTasks ', data);
                this.setState({tasks: data.data});
            },
            error => {
                console.log('Error', error);
            });
    }

    render() {
        return (
            <div className="App">
                <header className="App-header">
                    <img src={logo} className="App-logo" alt="logo"/>
                </header>
                <div align="center"><b>Tasks</b></div>
                <table align="center" border={1}>
                    <tr>
                        <td>id</td>
                        <td>name</td>
                    </tr>
                    {this.state.tasks.map(task =>
                        <tr>
                            <td>{task.id}</td>
                            <td>{task.name}</td>
                        </tr>
                    )}
                </table>

                <br></br><br></br><br></br>

                <div align="center"><b>Files</b></div>
                <table align="center" border={1}>
                    <tr>
                        <td>id</td>
                        <td>name</td>
                    </tr>
                    {this.state.files.map(file =>
                        <tr>
                            <td>{file.entry.id}</td>
                            <td>{file.entry.name}</td>
                        </tr>
                    )}
                </table>
            </div>
        );
    }
}

export default App;
